### ISSUE TITLE
Crash with Auxiliary Reaction Chamber applied to Steam Dynamo

### ISSUE THREAD

**Issue by rbaker87** [ChiefArug/ThermalSysteams#10]
I know this is generally frowned upon, but my setup is way too slow to test this on a fresh environment with only ThermalSysteams and its requirements. Using ATM8 1.0.22 with the latest version of Systeams (1.19.2-1.4.0 at the time of writing this), attempting to place an Auxiliary Reaction Chamber upgrade into a Steam Dynamo produces the following crash report.

The exact setup that reproduces this 100% of the time is a finite lava container (in this case, a mekanism fluid pump, but it works with others I have tried as well), connected to a pipe outputting lava into one side of a magmatic boiler (in this case - advanced mekanism pipes connected to a completely non-upgraded magmatic boiler on its right side). I then connected an infinite water source to the back side of the boiler (sink with mekanism pipes again). The Steam Dynamo is connected directly to the front of the Magmatic Boiler and as soon as the Auxiliary Reaction Chamber is applied the game crashes.

[crash-2023-07-11_15.20.16-server.txt](https://github.com/ChiefArug/ThermalSysteams/files/12021495/crash-2023-07-11_15.20.16-server.txt)

**Comment by ChiefArug** [comment]
Please when attaching crash reports upload them as files or use a paste site and provide a link, and do not cut the bottom off no matter how unimportant it seems to you.

**Comment by rbaker87** [comment]
> Please when attaching crash reports upload them as files or use a paste site and provide a link, and do not cut the bottom off no matter how unimportant it seems to you.

Updated.

**Comment by ChiefArug** [comment]
Thanky you. Should be an easy enough fix, tho I won't be able to do it for a few days.

**Comment by ChiefArug** [comment]
(not actually fixed for 1.18 yet)

**Comment by ChiefArug** [comment]
Now it is fixed.
https://www.curseforge.com/minecraft/mc-mods/systeams/files/4645097
