### ISSUE TITLE
[1.19.2] Server Config Reverts Itself

### ISSUE THREAD

**Issue by Brown-bricks** [ChiefArug/ThermalSysteams#13]
Certain changes to the server config are reverted after the world is reloaded. 

- Any increase in water_to_steam_ratio or steam_dynamo_output_multiplier is forced back to 2.0.
- Any increase in Steam Values is forced back to 0.5.

**Comment by ChiefArug** [comment]
Can you send the latest.log file please (use a paste site like https://gist.github.com), it has important information for diagnosing issues

**Comment by Brown-bricks** [comment]
Brief Update: I may be stupid, changes were reverted due to them being applied while the world was running. Thanks for the help, though!

**Comment by ChiefArug** [comment]
Weird. In theory forge configs should be hot autoreloadable like that.
