### ISSUE TITLE
Boiler's facing direction does not update properly when its block state is changed

### ISSUE THREAD

**Issue by cubebotfan** [ChiefArug/ThermalSysteams#16]
![2024-03-07_23 18 30](https://github.com/ChiefArug/ThermalSysteams/assets/150861277/53ce7b04-7f5e-454d-8824-46d7fa1514e7)

boilers that have their block state modified (through crecent hammer or other means) Will continue to output steam to where they were originally facing until the world is reloaded.

I'm pretty sure this issue is caused by the direction being cached in BoilerBlockEntityBase. The direction the boiler is facing doesn't seem to ever get updated unless the world is unloaded and reloaded. I am an idiot when it comes to modding though so I could be wrong about this.

steps to reproduce:
-place a boiler
-rotate it using a crescent hammer (or other means)
-give it water and fuel
-instead of outputing to the side it is facing, it will output to the side it was originally facing the moment it was placed

Reloading the world fixes this until the boiler gets rotated again

**Comment by ChiefArug** [comment]
Whoops, looks like I forgot to call updateFacing in a couple places. I'll have a look at how thermal does it for dynamos and hopefully have time to fix this within the next week.

**Comment by ChiefArug** [comment]
Fixed and released: https://www.curseforge.com/minecraft/mc-mods/systeams/files/5188994
