### ISSUE TITLE
Boilers are not waterloggable

### ISSUE THREAD

**Issue by cubebotfan** [ChiefArug/ThermalSysteams#18]
Boilers are not waterloggable.
Dynamos are waterloggable. Absolutely unplayable.

**Comment by ChiefArug** [comment]
I'm pretty sure they are, its just a lot harder to actually waterlog them cause you can stick water in them as well as around them.

**Comment by ChiefArug** [comment]
They are waterloggable, but only if you place the boiler in water, not if you place the water around the boiler. I'll see about fixing that soon.
