### ISSUE TITLE
[Suggestion] Custom working fluid recipes for boilers

### ISSUE THREAD

**Issue by vertexcubed** [ChiefArug/ThermalSysteams#21]
As the title says, it'd be interesting if pack developers could make recipes that use fluids other than water in the boilers to produce whatever fluid, so for example mercury or CO2 or magical fuels (these would basically be gas turbines at that point but those are just examples)

**Comment by ChiefArug** [comment]
This would go quite well with a JEI tab for how much energy is required to turn water to steam, which I have been planning on doing. It might be a while till I have time to implement it though.

**Comment by ChiefArug** [comment]
Also a good excuse to do #17 which I have been putting off
