### ISSUE TITLE
[Feature Request] Raise the limit of water_to_steam_ratio config option

### ISSUE THREAD

**Issue by Xefyr0** [ChiefArug/ThermalSysteams#22]
In particular, my objective is trying to fit Steam compatibility with Gregtech on 1.20.1.
Gregtech's ratio of units steam per unit water in any boiler or fluid heater recipe is _one hundred and sixty._ This far exceeds Systeams' maximum of 10, but is still far below the IRL ratio of around 1700. Please raise the limit of water_to_steam_ratio. Maybe a new maximum of 1-2 thousand would cover all use cases?

**Comment by ChiefArug** [comment]
Duplicate of https://github.com/ChiefArug/ThermalSysteams/issues/14
Also see https://github.com/ChiefArug/ThermalSysteams/pull/15
Also see https://github.com/ChiefArug/ThermalSysteams/issues/17

**Comment by Xefyr0** [comment]
Ah. my apologies. I should have checked the closed issues.
