### ISSUE TITLE
1.19.2 Thermal Systeams has failed to load(server only)

### ISSUE THREAD

**Issue by Enterprise12nx01** [ChiefArug/ThermalSysteams#24]
Added this to my server with the latest update and its crashing, it has had no issues client side
crash report: https://pastebin.com/x1ppCMUk
latest.log: https://pastebin.com/VRAbTGcS

**Comment by ChiefArug** [comment]
Oops, looks like I load something I shouldn't. I'll get a fix out asap

**Comment by ChiefArug** [comment]
Fixed and released https://www.curseforge.com/minecraft/mc-mods/systeams/files/5744820
