### ISSUE TITLE
Add support for Electrodynamics/Nuclear Science 

### ISSUE THREAD

**Issue by gfbbkon** [ChiefArug/ThermalSysteams#25]
https://www.curseforge.com/minecraft/mc-mods/electrodynamics
https://www.curseforge.com/minecraft/mc-mods/nuclear-science
Title says all

**Comment by ChiefArug** [comment]
Support how? What sort of things do those mods add that could be supported in Systeams?

**Comment by ChiefArug** [comment]
Closing for lack of information. If anyone has more context as to what in those mods needs support, I will reopen this.
