### ISSUE TITLE
Steam fluid conflicts lock up mixed-generation seam power setups in Monifactory

### ISSUE THREAD

**Issue by unktheunk** [ChiefArug/ThermalSysteams#26]
The issue here is already touched on in #17 and #21, just wanted to add on that allowing custom fluid generation via the configs would help pack devs with compatibility stuff.

I was able to fix my power setup by only using the GT solar boilers, but allowing more custom stuff would be cool and good. Just a thing to keep in mind for when/if #17 is done.

:)

**Comment by ChiefArug** [comment]
If you have something to add to another issue please use a comment.

As for how Systeams works in <modpack>, you should talk to the pack authors about that (and if they want changes in systeams to support that, they can make an issue or pr the change) or genrify it so you dont need to mention a specific pack. Also its nice to be specifc about stuff, I have no idea what or how 'GT solar boilers' work or how they could interact and be compatible with Systeams.
