### ISSUE TITLE
Boilers do not export steam into pipes

### ISSUE THREAD

**Issue by Bazyliii** [ChiefArug/ThermalSysteams#5]
Like in the title, I was messing around with thermal stuff on creative, and when I wanted to try your mod boilers, I noticed that they couldn't export stream into pipes. I tried Mekanism, Create, Pipez pipes and nothing was working.

![2023-02-25_01 40 42](https://user-images.githubusercontent.com/67436562/221326102-62aa26c8-0635-4289-94f6-da0ed815f9b6.png)

**Comment by ChiefArug** [comment]
That is strange... Do other thermal (non systeams) things work with pipes?

**Comment by ChiefArug** [comment]
Fixed in dev

**Comment by ChiefArug** [comment]
Fixed in 1.2.2
https://www.curseforge.com/minecraft/mc-mods/systeams/files/4412036
