### ISSUE TITLE
game crashes directly after shift clicking a dynamo to convert it to a boiler

### ISSUE THREAD

**Issue by clectico** [ChiefArug/ThermalSysteams#9]
displays as a 'Exception in server tick loop' eror in crash log

also it occured with a stirling dynamo if that matters

**Comment by ChiefArug** [comment]
can you please provide the full crash report or logs?

**Comment by clectico** [comment]
[crash-2023-06-18_21.26.59-server.txt](https://github.com/ChiefArug/ThermalSysteams/files/11784070/crash-2023-06-18_21.26.59-server.txt)

**Comment by ChiefArug** [comment]
That is not the full report, you cut off the bottom.

**Comment by ChiefArug** [comment]
Managed to reproduce this by removing PNC:R. Fixed in 1.4.0 (https://www.curseforge.com/minecraft/mc-mods/systeams/files/4599922 once approved).
